version: '3.5'
services:

##Home Assistant##
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /opt/homeassistant:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Chicago
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rwm
    restart: always
    network_mode: host
    privileged: true

##Emby##
  emby:
    image: emby/embyserver
    container_name: embyserver
    #runtime: nvidia # Expose NVIDIA GPUs
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /opt/emby:/config # Configuration directory
      - /media/netstore:/mnt/share1 # Media directory
      - /media/qnap:/mnt/share2 # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    #devices:
    #  - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    #  - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: unless-stopped
  ##Plex##
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=claim-XXXXXXXXXXXXXXXX
    network_mode: host
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/transcode:/transcode
      - /media/qnap:/data
